name: CI + CD


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!
  deployDev:
    name: Deploy to dev
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: 'Deploy ARM Template'
        run: |
          az deployment group create \
            --name demoRGDeployment \
            --resource-group githubactionspoc-rg \
            --template-uri "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.storage/storage-account-create/azuredeploy.json" \
            --parameters storageAccountType=Standard_GRS
  deployQA:
    name: Deploy to Production 
    needs: [deployDev]
    runs-on: ubuntu-latest
    environment: 
      name: QA
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
  deployUAT:
    name: Deploy to Production 
    needs: [deployQA]
    runs-on: ubuntu-latest
    environment: 
      name: UAT
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 

  deployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: 'Deploy ARM Template'
        run: |
          az deployment group create \
            --name demoRGDeployment \
            --resource-group githubactionspoc-rg \
            --template-uri "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.storage/storage-account-create/azuredeploy.json" \
            --parameters storageAccountType=Standard_GRS
  deployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 

